### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mikejnpc** [tm31420/Secp256K1-4-all#1]
Can you suggest why it going out of range?

/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "crackRSZ.py", line 115, in <module>
    matrix = make_matrix(msgs,sigs,c)
  File "crackRSZ.py", line 64, in make_matrix
    x0=(sigs[i+c][0] * modular_inv(sigs[i+c][1], order)) - rnsn_inv
IndexError: list index out of range

Do i need to alter the lib, as far as understood it, just a warning. 

Thank you.

**Comment by mikejnpc** [comment]
okay i guess i had a space which was throwing it off ... :)

**Comment by tm31420** [comment]
:+1: :+1:

**Comment by bust1** [comment]
hi how can i use it please ?
